### ISSUE TITLE
Make fails b\c of missing sstream library

### ISSUE THREAD

**Issue by iCurlmyster** [matt-42/silicon#10]
When I first ran the install.sh for the project it failed because in the file 

silicon_build/externals/iod/tools/iod_generate_symbols.cc

it is missing the sstream library and because you use a stringstream object it complained and didn't finish the install. Once I added that library in the file everything installed successfully. So if people have trouble with installing the project, this could be the problem their having.

**Comment by matt-42** [comment]
Thank you. It was compiling on linux but you are right the header sstream was missing. I just added it in https://github.com/matt-42/iod/commit/c1580a5a017e357cd1d947118c22de2c650a2873
