### ISSUE TITLE
add lwan as a backend?

### ISSUE THREAD

**Issue by byzhang** [matt-42/silicon#12]
Could you please consider adding lwan (https://github.com/lpereira/lwan) as a backend? lwan has some good performance optimization e.g. cpu branch prediction, json encoder/decoder, and hence faster than MHD in several benchmark tests.

**Comment by matt-42** [comment]
I finished a first implementation. It should be included in the next techempower framework benchmark round.
https://github.com/matt-42/silicon/commit/892d2b8f0397caec9029f029cabdb9f6c1caf717
