### ISSUE TITLE
optional parameters in request?

### ISSUE THREAD

**Issue by byzhang** [matt-42/silicon#16]
from https://github.com/matt-42/iod, it seems we can use named optional function arguments to do it, but could you please give a simple example on the right syntax?

**Comment by matt-42** [comment]
Just mark your argument with the _optional symbol:
```c++
_argX(_optional) = int()
```

**Comment by byzhang** [comment]
Thanks, it also works. A related question is how to assign the default value? I tried 
```
_argX(_optional) = std::string("some_default_value")
```
And it doesn't work.

**Comment by byzhang** [comment]
Another relevant question, does Iod support enum (class)? 
I tried
```
enum class Gender {
MALE,
FEMALE
};
_argX = Gender()
```
it seems not compilable.

**Comment by byzhang** [comment]
Back to the optional, how to check whether an optional arg is set or not?
```
_my_scope = D(_test2(_name=D(_first=std::string(), _second(_optional)=std::string()), _gender=int()) = [] (auto p) {
  return D(_message = "hello " + p.name.first + " " + (p.name.has(_second)? p.name.second: "default"));
})
```
Here is the result:
```
curl "http://127.0.0.1:23456/my_scope/test2" -H "Content-Type: application/json" --data '{"name":{"first": "a"}, "gender":1}'
{"message":"hello a "}%
```
It seems the p.name.has(_second) is true, but p.name.second has the default value "".

**Comment by matt-42** [comment]
As of today, there is no way to check whether the optional arg has been set. I am thinking about how to implement it. The best solution to me would be to use something like boost::optional to store the optional fields...

**Comment by matt-42** [comment]
It is now possible, here is an example:
https://github.com/matt-42/silicon/blob/master/tests/optional.cc
