### ISSUE TITLE
link error when compiling benchmark/

### ISSUE THREAD

**Issue by byzhang** [matt-42/silicon#18]
A lots of errors like:
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(sha-x86-ssse3.o):(.data.rel.ro+0x18): undefined reference to `nettle_sha256_init'

I have nettle_dev and libnettle4 installed. What else are missing?

**Comment by matt-42** [comment]
What did you try to compile? An silicon example or your own code?

**Comment by byzhang** [comment]
benchmark/silicon_epoll_mysql

**Comment by matt-42** [comment]
Could you post here the compilation log? I could not reproduce the problem.

**Comment by byzhang** [comment]
I guess I missed something in your thirdparty folder.
Here is the verbose output:

Linking CXX executable silicon_epoll_mysql


                                   [668/9823]
cd /home/byzhang/src/silicon/build/benchmark && /usr/bin/cmake -E
cmake_link_script CMakeFiles/silicon_epoll_mysql.dir/link.txt --verbose=1
/usr/bin/g++   -std=c++1y -march=x86-64 -m64 -Winline
-fno-omit-frame-pointer -fPIC -I/usr/local/include -Wall -Wextra
-Woverloaded-virtual -Wno-unused-local-typedefs --param
inline-unit-growth=150 --param max-inline-insns-single=500 --param
large-function-growth=600 -O3
-DNDEBUG    CMakeFiles/silicon_epoll_mysql.dir/main.cpp.o  -o
silicon_epoll_mysql -rdynamic -Wl,-Bstatic -lmicrohttpd -lgnutls -lgcrypt
-lgpg-error -lz -lm -ltasn1 -lstdc++ -Wl,-Bdynamic -lp11-kit -lpthread
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(gnutls_state.o):
In function `_gnutls_PRF':
(.text+0x1146): undefined reference to `memxor'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(cipher.o):
In function `wrap_nettle_cipher_init':
(.text+0x1a1): undefined reference to `nettle_camellia_crypt'
...
...
...
usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(sha-x86-ssse3.o):(.
data.rel.ro+0x18): undefined reference to `nettle_sha256_init'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(sha-x86-ssse3.o):(.
data.rel.ro+0x28): undefined reference to `nettle_sha256_digest'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(sha-x86-ssse3.o):(.
data.rel.ro+0x58): undefined reference to `nettle_sha224_init'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(sha-x86-ssse3.o):(.
data.rel.ro+0x68): undefined reference to `nettle_sha224_digest'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(sha-x86-ssse3.o):(.
data.rel.ro+0x98): undefined reference to `nettle_sha1_init'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnutls.a(sha-x86-ssse3.o):(.
data.rel.ro+0xa8): undefined reference to `nettle_sha1_digest'
collect2: error: ld returned 1 exit status

Thanks,
-B

On Wed, Sep 9, 2015 at 1:29 PM, Matthieu Garrigues <notifications@github.com

**Comment by matt-42** [comment]
The benchmark folder is not longer in the silicon repository. If you want to benchmark the framework, you can git pull and compile the programs in the examples directory. 

However, if you really want to compile silicon_epoll_mysql, check the FrameworkBenchmark repository: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C%2B%2B/silicon
