### ISSUE TITLE
Better documentation to compile the hello world example

### ISSUE THREAD

**Issue by rjammala** [matt-42/silicon#2]
Hi 

Can you please provide better documentation to compile the hello world example?

I tried the following and get errors.

I am using the following compiler:

$ g++ --version
g++-4.9.real (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~/SILICON/bin/iodc hello_world.cpp hello_world_transformed.cpp
 g++ -Wall -Wextra  -std=c++1y -I/home/user/SILICON/include hello_world_transformed.cpp 

In file included from /home/user/SILICON/include/silicon/mhd_serve.hh:9:0,
                 from hello_world_transformed.cpp:3:
/home/user/SILICON/include/silicon/service.hh: In member function ‘virtual void sl::handler<A, R, F, M, S>::operator()(M&, S&, sl::handler<A, R, F, M, S>::request_type&, sl::handler<A, R, F, M, S>::response_type&)’:
/home/user/SILICON/include/silicon/service.hh:51:50: warning: typedef ‘T’ locally defined but not used [-Wunused-local-typedefs]
       typedef iod::callable_arguments_tuple_t<F> T;
                                                  ^
In file included from hello_world_transformed.cpp:3:0:
/home/user/SILICON/include/silicon/mhd_serve.hh: In function ‘int sl::mdh_keyvalue_iterator(void*, MHD_ValueKind, const char*, const char*)’:
/home/user/SILICON/include/silicon/mhd_serve.hh:67:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
hello_world_transformed.cpp: At global scope:
hello_world_transformed.cpp:10:6: error: ‘_hello’ is not a member of ‘s’
      s::_hello= [] () { return D(s::_message= "hello world.");}
      ^
hello_world_transformed.cpp: In lambda function:
hello_world_transformed.cpp:10:34: error: ‘_message’ is not a member of ‘s’
      s::_hello= [] () { return D(s::_message= "hello world.");}

**Comment by matt-42** [comment]
The cmake rules add_iod_executable automatically call the preprocessor but you can still compile it without cmake. You are only missing the first C preprocessor pass:

g++ -E main.cc  -I ../install/include/ -std=c++14  -o main2.cc
../install/bin/iodc main2.cc main3.cc
g++ -std=c++14 main3.cc   -I ../install/include/  -lmicrohttpd -o hello_world

You can also try the plain c++ version of hello_world 

```c++
#include <iod/symbol.hh>

iod_define_symbol(hello, _hello);
iod_define_symbol(message, _message);

#include <silicon/api.hh>
#include <silicon/mhd_serve.hh>

using namespace sl;

// Define the API:
auto hello_api = make_api(

  // The hello world procedure.
  s::_hello = [] () { return D(s::_message = "Hello world."); }

);

int main()
{
  // Serve hello_api via microhttpd using the json format:
  sl::mhd_json_serve(hello_api, 12345);
}
```

**Comment by matt-42** [comment]
The compilation of hello_world with CMake is documented here: 
https://github.com/matt-42/silicon#compilation
