### ISSUE TITLE
MHD_http_unescape not available on homebrew OSX libmicrohttpd

### ISSUE THREAD

**Issue by ahupowerdns** [matt-42/silicon#21]
Hi Matthieu, 

First thank you VERY much for this library, it is pretty exciting, and I'm hoping to use it a lot. To get it to work, I had to comment out (!) the call to MHD_http_unescape in mhd.hh (which effectively breaks unescaping of course). My 'homebrew' ships version 0.9.38 which does not appear to come with a user-visible unescape function.

I'm trying to figure out what the best thing to do is here, but maybe you have some ideas already.

Again, thanks for Silicon!

**Comment by matt-42** [comment]
Hi Bert,

Thanks for your interest in silicon :) A friend also reported me this problem few weeks ago. That's a shame that distros keep such an old version of microhttpd. I do not have an idea yet but you can easily compile the newest version available here https://ftp.gnu.org/gnu/libmicrohttpd/  Is this fine for you ?

**Comment by moshen** [comment]
It looks like the version in homebrew has been updated: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libmicrohttpd.rb

**Comment by matt-42** [comment]
Thanks moshen for the notice. I suppose we can close this issue then.
