### ISSUE TITLE
application/json

### ISSUE THREAD

**Issue by tex** [matt-42/silicon#24]
I'm plaing with rest.cc from tests and it seems to accept application/x-www-form-urlencoded only.
How to accept application/json as input?

**Comment by tex** [comment]
And thanks for very nice C++ framework!

**Comment by matt-42** [comment]
Hi Tex,
I'm working on it.

**Comment by matt-42** [comment]
You can now use the application/json content-type as input: check this commit: e02c1ee222bac41ab8a4d58c5f713b30d2ec7e24

https://github.com/matt-42/silicon/commit/e02c1ee222bac41ab8a4d58c5f713b30d2ec7e24#diff-ca334d1611153b304440f66073607b47R221
