### ISSUE TITLE
"type_string" output of vector

### ISSUE THREAD

**Issue by 84356813** [matt-42/silicon#29]
`#include \<iostream\>
#include \<silicon/api.hh\>
#include \<silicon/api_description.hh\>
#include "symbols.hh"

using namespace sl; // Silicon namespace
using namespace s; // Symbols namespace

int main()
{
    typedef decltype(D(_name = std::string(), _age = int(), _city = std::string())) User;

    User u("John", 23, "NYC");
    std::vector<User> ul;
    ul.push_back(u);
    std::cout << "-----type_string(User)-----" <<std::endl;
    std::cout << type_string( &u ) <<std::endl;
    std::cout << "-----type_string(std::vector<user>)-----" <<std::endl;
    std::cout << type_string( &ul ) <<std::endl;

    return 0;
}`

out put :
```
-----type_string(User)-----
{name: string, age: int, city: string}
-----type_string(std::vector<user>)-----
vector of void
```
Is there some way to make "type_string(std::vector<user>*)" to output "vector of {name: string, age: int, city: string}"

**Comment by matt-42** [comment]
It should work now: https://github.com/matt-42/silicon/commit/9741159a5cb0133f62cd6f930781bd8707c28904#diff-60cb1e143f8c8fa9e4aca20cab1f6a50R36

**Comment by 84356813** [comment]
it works,but not so well.
`#include \<iostream\>

#include \<silicon/api.hh\>
#include \<silicon/api_description.hh\>

#include "symbols.hh"


using namespace sl; // Silicon namespace
using namespace s; // Symbols namespace

int main()
{
    typedef decltype(D(_name = std::string(), _age = int(), _city = std::string())) User;

    User u("John", 23, "NYC");
    std::vector<User> ul;
    ul.push_back(u);
    auto x = D(_num=1,_date=ul);
    std::cout << "-----type_string(User)-----" <<std::endl;
    std::cout << type_string( &u ) <<std::endl;
    std::cout << "-----type_string(std::vector<user>)-----" <<std::endl;
    std::cout << type_string( &ul ) <<std::endl;
    std::cout << "-----type_string(D(_num=int(1),_date=std::vector<user>()))-----" <<std::endl;
    std::cout << type_string(&x) <<std::endl;
    return 0;
}
`
out put:

`-----type_string(User)-----
{name: string, age: int, city: string}
-----type_string(std::vector<user>)-----
vector of {name: string, age: int, city: string}
-----type_string(D(_num=int(1),_date=std::vector<user>()))-----
{num: int, date: vector of void}
`
when a vector nesting in a sio, it does not work again;

**Comment by matt-42** [comment]
Thanks for noticing. Fixed in https://github.com/matt-42/silicon/commit/e54e174e5eea17ecfd5805ff7b45e3711a8f0030
