### ISSUE TITLE
Cannot serialize the integer zero to json in response

### ISSUE THREAD

**Issue by Kazuo256** [matt-42/silicon#37]
If a procedure tries to return a SIO object with fields that carry the value zero, they will appear as empty strings on the HTTP response body. For instance:

```c++
return D(_foo = 0);
```

Will be serialized to `{"foo":}`.

Is this the intended behaviour?

Edit: [it seems the error is in the iod library](https://github.com/matt-42/iod/issues/14). Should I close this?

**Comment by fnc12** [comment]
Had the same issue. Changed serialization to [nlohmann::json](https://github.com/nlohmann/json)
