### ISSUE TITLE
double as post parameter throws ::boost::bad_lexical_cast

### ISSUE THREAD

**Issue by fnc12** [matt-42/silicon#38]
```c++
POST / _product_in_stock * post_parameters(_product_id = int(),
                                          _price = double()) = [] (auto p) {
   cout << "price = " << p.price << endl;
}
```

Next implementing request:
**URL =** http://192.168.1.10/product_in_stock
**Headers =** Content-Type:application/json
**Method =** POST
**Body:**
```
{
	"product_id":1,
	"price":1.5
}
```

Exception is thrown:

libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> >: bad lexical cast: source type value could not be interpreted as target

**Comment by vidcentum** [comment]
I tried the above example. It ran successfully and printed "price = 1.5" on the console output.

**Comment by tex** [comment]
Does your locale use , as separator?

**Comment by fnc12** [comment]
@tex I think yes. How to identify it?

**Comment by matt-42** [comment]
All json parsing errors are now catched by the MHD backend : https://github.com/matt-42/silicon/commit/e0616156290c36fc1cd9ddd21a0ef46a8de786d8
The parsing of number will still use your locale but at least it won't make the server crash anymore.
