### ISSUE TITLE
How to enable ssl?

### ISSUE THREAD

**Issue by fnc12** [matt-42/silicon#39]
I want to use a secured connection in case if someone listens to internet traffic to keep access token safe. How to perform this thing with silicone framework?

**Comment by matt-42** [comment]
Today the only way is to place silicon behind a ssl enabled nginx. I'll update the silicon backend this week so that you can use the MHD backend with SSL.

**Comment by matt-42** [comment]
It is now possible with
https://github.com/matt-42/silicon/commit/37775916d835a9433a138fc843fcb1be634f17f4

Checkout this example :
https://github.com/matt-42/silicon/blob/master/examples/https.cc
