### ISSUE TITLE
file server example required

### ISSUE THREAD

**Issue by fnc12** [matt-42/silicon#40]
Hey matt-42. silicon framework is one of the coolest thing I had ever seen and used. I saw today you commited a file streaming feature. Could you please provide an example of how to implement this? Thanks

**Comment by matt-42** [comment]
Thanks fnc12! Here is the example:
https://github.com/matt-42/silicon/blob/master/examples/file_streaming.cc

**Comment by matt-42** [comment]
Hi, 
In case it suits better your need, it is now possible to serve a whole directory in one shot : https://github.com/matt-42/silicon/blob/master/tests/static_file_server.cc
