### ISSUE TITLE
Custom Paths

### ISSUE THREAD

**Issue by GuacheSuede** [matt-42/silicon#45]
Hi Matt, 
how does one go about writing custom paths such as `/hello/John` and getting John as a param ?

Thank You

**Comment by matt-42** [comment]
Here is a small API doing what you want:
auto hello_api = http_api(
  GET / _hello / _name[std::string()] = [] (auto params) { return "hello " + params.name; }
);

Does it answer your question ?

**Comment by GuacheSuede** [comment]
Thank you Matt, yes it does.

Quick question, i notice alot of commented out code in lwan.hh, what does that mean ? 
Also, lwan is no longer compatible with Silicon due to breaking changes, mass renames of lwan variables

**Comment by matt-42** [comment]
It's true that I did not work on it since quite some time. I'll revamp it if you need it.
In the meantime, you can use the mhd backend which is more stable and up to date.

**Comment by GuacheSuede** [comment]
Alright sure, i made some changes to the official lwan repo(merged) to fix some breaking changes, you are mostly left to deal with variable renames. 

Would you consider officially supporting the lwan backend, on the TechEmpower benchmark, it trumps every other webserver including mhd, lwan has a good history of commits and active

**Comment by matt-42** [comment]
Lwan compile with my last commit 5737203892094ed2685e1bd9718ddf189d6afb61, and with another C++ fix I've submitted to Lwan's master.
 
I included LWAN in the techempower 13th round : https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=db&l=4fs3jz
It was able to better handle the heavy load of the plaintext example (up to 16k connections), but it was pretty much on par with MHD on the other tests.

**Comment by GuacheSuede** [comment]
@matt-42 Thank you for the changes, made some further compilation changes

**Comment by matt-42** [comment]
Keep in mind that POST requests does not work anymore. I don't know yet if it's due to silicon or lwan.

**Comment by GuacheSuede** [comment]
@matt-42 I am testing lwan now, POSTS definitely works on LWAN, using your commit. Do inform me  if you need any help on the lwan side :)
