### ISSUE TITLE
Add `Content-Type: application/json` to response

### ISSUE THREAD

**Issue by fnc12** [matt-42/silicon#51]
How to add a header `Content-Type: application/json` to response? Maybe it would be more logically to insert it implicitly?

**Comment by matt-42** [comment]
You can do it manually, check here:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C%2B%2B/silicon/techempower.hh#L47

Good suggestion, I'll insert it implicitely for procedures returning SIO objects.
