### ISSUE TITLE
[Error] websocketpp/config/asio_no_tls.hpp: No such file or directory

### ISSUE THREAD

**Issue by dshahrokhian** [matt-42/silicon#52]
During compilation, I get the following error:

`/usr/local/include/silicon/backends/websocketpp.hh:7:46: fatal error: websocketpp/config/asio_no_tls.hpp: No such file or directory compilation terminated.`

I cannot find such file anywhere in the repo. Am I supposed to install `websocketpp` separately or something? It doesn't appear in the [installation page](http://siliconframework.org/docs/getting_started.html).

For instance, how should I compile the example `ws_broadcast_server.cc`?

**Comment by dshahrokhian** [comment]
Indeed, the problem is that `websocketpp` is missing in the specification. You need to install it as well.

**Comment by matt-42** [comment]
I added a note about this in 2faac332cef41b3c659f9bc79311bd3152c3f0a7
