### ISSUE TITLE
ws_broadcast_server.cc broadcast all clients from the server?

### ISSUE THREAD

**Issue by dshahrokhian** [matt-42/silicon#53]
Is there any way in which through the example `ws_broadcast_server.cc` the server can trigger a broadcast to all clients, without the need of a client sending a message?

**Comment by matt-42** [comment]
I never really tried this before, but it seems that websocketpp is thread safe.
So you probably can spawn a thread that runs

```c++
for (const wspp_connection& c : users) rclient(c).message(your_message);
```
(see the definition of rclient here: https://github.com/matt-42/silicon/blob/master/examples/ws_broadcast_server.cc)

whenever you need to.

**Comment by dshahrokhian** [comment]
Thank you Matthieu.
