### ISSUE TITLE
Possibility to add a custom HTTP header ?

### ISSUE THREAD

**Issue by zxvfxwing** [matt-42/silicon#59]
Hi,

I wanted to know if it's possible to add a custom HTTP header for response-header -- I mean, to the server (I'm using Ajax to get data from C++ API).

My only solution here, is to make Silicon running behind a reverse proxy (nginx, where I can put the custom header).

Thank you.

**Comment by matt-42** [comment]
Yes this is possible with the mhd backend:
[] (mhd_response* r)
  {
    req->set_header("header_key", "value");
  });

**Comment by zxvfxwing** [comment]
Can I have an example more specific please ?

i.e: 

```c++
GET / _login * get_parameters(_id = int())  = [] (auto param) {
    return param.id;
}
```

Where do I place the `mhd_response` ?

Thank you.

**Comment by matt-42** [comment]
Just add it to the parameter:  [] (auto param, mhd_response* r) {

**Comment by zxvfxwing** [comment]
Thank you, it's actually working great 👍
