### ISSUE TITLE
get your benchmarks onto techempower.com

### ISSUE THREAD

**Issue by solmetricchris** [matt-42/silicon#6]
https://www.techempower.com/benchmarks/

This is the most comprehensive set that I know of.

I'm not associated in anyway.

**Comment by matt-42** [comment]
I'm working on it. I just need to add the handling of GET parameters... (As of today, the procedures only take arguments from the request body), and finish utf8.

**Comment by matt-42** [comment]
I finished the implementation of the benchmark. Here is the pull request:
https://github.com/TechEmpower/FrameworkBenchmarks/pull/1426

**Comment by KrishnaPG** [comment]
Wondering if this is done - could not see silicon on the benchmark results

**Comment by matt-42** [comment]
answered here: https://github.com/TechEmpower/FrameworkBenchmarks/pull/1426#issuecomment-225793926
