### ISSUE TITLE
Can global middlewares access request & response?

### ISSUE THREAD

**Issue by lythesia** [matt-42/silicon#70]
For example, we can log time consume for each request with its req path and body included Or we can modify response after request completed

**Comment by matt-42** [comment]
Yes, just add those as  parameter of the middleware instantiate method:
``` instantiate(mhd_request& request, mhd_response& response)```

**Comment by lythesia** [comment]
It works! Thank you.
I'll take look at the `instantiate` method.

**Comment by lythesia** [comment]
One more question: can we access route info also (so we can log http verb then)? Maybe not possible for now (?)
The route `R` hides in `prefix_path_middleware<R>`, but GA's instantiate method cannot be templated. (It seems that accessible args in taglist when instantiate GA must not be dependenty types?)

**Comment by matt-42** [comment]
Not yet, I'll add it in the mhd_request object.
Matthieu Garrigues

**Comment by lythesia** [comment]
Thanks!
